### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by neericks** [tdscott10/Tetris#38]
Boring game play without music.  Add background music, line clear sound effect, and level up sound effect.

**Comment by neericks** [comment]
UPDATE:
I have the original Tetris theme music looping during play as well as a sound effect for when lines are cleared.  I am working on making the music pause along with the 'P' button and will hopefully have that done soon.
I am trying to add an effect to play when it levels up, but am having issues with that one.

**Comment by neericks** [comment]
UPDATE:
I have the original Tetris theme music looping during play as well as a sound effect for when lines are cleared. Thus far, unsuccessful in getting music to pause along with 'P.'
I added code to the line 398 in Tetris.class that should play a sound effect when the level variable is changed, however I am not sure how to implement it properly, I think it maybe needs to be a Change Listener.

**Comment by tdscott10** [comment]
Audio is working in the executable jar. Closing this issue
